from __future__ import annotations

import json

from saxo_bank_mcp._evidence import JsonValue


def banner(title: str, source_hash: str) -> list[str]:
    return [
        f"# {title}",
        "",
        "<!-- GENERATED by scripts/generate_agent_skill_catalogs.py. Do not edit. -->",
        f"<!-- source_sha256={source_hash} -->",
        "",
    ]


def cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def code(value: JsonValue) -> str:
    dumped = json.dumps(value, sort_keys=True, separators=(",", ":"))
    return "`" + dumped.replace("|", "\\|") + "`"
